project:
  type: website

website:
  title: "IS415_GAA"
  navbar:
    left:
      - text: "Hands-on Exercise"
        menu: 
          - text: "Hand-on Exercise 1"
            href: "./Hands_On_Ex/Hands_On_Ex01/Hands_On_Ex01.html"



            
      - text: "In Class Exercise"
        menu:
          - text: "In Class Exercise 2"
            href: "./InClass/InClassWeek2/InClass2.html"  
          - text: "In Class Exercise 3"
            href: "./InClass/InClassWeek3/InClass3.html" 
  
  


    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual
