project:
  type: website

website:
  title: "IS415_GAA"
  navbar:
    left:
      - text: "Hands-on Exercise"
        menu: 
          - text: "Hand-on Exercise 1"
            href: "./Hands_On_Ex/Hands-on_Ex01/Hands_On_Ex01.html"      - text: "Hands-on Exercise"
        menu: 
          - text: "Hand-on Exercise 2"
            href: "./Hands_On_Ex/Hands-on_Ex02/Hands_On_Ex02.html"
        menu: 
          - text: "Hand-on Exercise 3"
            href: "./Hands_On_Ex/Hands-on_Ex03/Hands_On_Ex03.html"
        menu: 
          - text: "Hand-on Exercise 4"
            href: "./Hands_On_Ex/Hands-on_Ex04/Hands_On_Ex04.html"     
        menu: 
          - text: "Hand-on Exercise 5"
            href: "./Hands_On_Ex/Hands-on_Ex05/Hands_On_Ex05.html"  
        menu: 
          - text: "Hand-on Exercise 6"
            href: "./Hands_On_Ex/Hands-on_Ex06/Hands_On_Ex06.html"  
        menu: 
          - text: "Hand-on Exercise 7"
            href: "./Hands_On_Ex/Hands-on_Ex07/Hands_On_Ex07.html"              
        menu: 
          - text: "Hand-on Exercise 8"
            href: "./Hands_On_Ex/Hands-on_Ex08/Hands_On_Ex08.html" 

            
      - text: "In Class Exercise"
        menu:
          - text: "In Class Exercise 2"
            href: "./InClass/InClassWeek2/InClass2.html"  
          - text: "In Class Exercise 3"
            href: "./InClass/InClassWeek3/InClass3.html"   
  
      - text: "Take Home Assignment"
        menu:
          - text: "Assignment 1"
            href: "./Take Home Assignment/TakeHome1.html"  
          - text: "Assignment 2"
            href: "./Take Home Assignment 2/Take-home_Ex02.html"  

  


    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual
